version: "3"
services:
  url_shortener_app:
    build: .
    ports:
      - "3009:3009"
      - "9228:9228"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - url_shortener_db

  url_shortener_db:
    image: "mongo:latest"
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
